name: Linter Check

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Installs the project dependencies
        run: poetry install
      - name: Run linter check
        run: make lint
