name: Linter Check

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install poetry
        run: make poetry-install
      - name: Install the project dependencies
        run: make install
      - name: Run linter check
        run: make lint
